/**
 * A QR encoder, in-house.
 *
 * The site ships no runtime dependencies — that is the standing rule, and a
 * QR library would be the first. The format is a published standard
 * (ISO/IEC 18004) and the whole encoder is table-driven, so writing it is a
 * bounded exercise rather than an open-ended one.
 *
 * Scope is deliberately narrow: byte mode, error-correction level M, one
 * function that returns a matrix of modules. That is everything a share link
 * needs. Byte mode encodes any URL without the alphanumeric mode's
 * uppercase-only restriction; level M (≈15% recovery) is the usual choice for
 * a code that will be photographed off a screen at an angle. Supporting the
 * other three levels would triple the block table below and buy nothing.
 *
 * `tests/core/qr.test.ts` checks the output module-for-module against vectors
 * produced by an independent reference encoder, which is the only way to know
 * this is right — a QR that is subtly wrong still looks exactly like a QR.
 */

/** Per version (1-40, index 0 = version 1): EC codewords per block, then the
 *  block groups as [blockCount, dataCodewordsPerBlock]. Two groups appear
 *  where the spec splits a version into blocks of two different sizes.
 *  Transcribed from the standard's block table. */
const RS_BLOCKS: ReadonlyArray<readonly [number, ReadonlyArray<readonly [number, number]>]> = [
  [10, [[1, 16]]], [16, [[1, 28]]], [26, [[1, 44]]], [18, [[2, 32]]],
  [24, [[2, 43]]], [16, [[4, 27]]], [18, [[4, 31]]], [22, [[2, 38], [2, 39]]],
  [22, [[3, 36], [2, 37]]], [26, [[4, 43], [1, 44]]], [30, [[1, 50], [4, 51]]],
  [22, [[6, 36], [2, 37]]], [22, [[8, 37], [1, 38]]], [24, [[4, 40], [5, 41]]],
  [24, [[5, 41], [5, 42]]], [28, [[7, 45], [3, 46]]], [28, [[10, 46], [1, 47]]],
  [26, [[9, 43], [4, 44]]], [26, [[3, 44], [11, 45]]], [26, [[3, 41], [13, 42]]],
  [26, [[17, 42]]], [28, [[17, 46]]], [28, [[4, 47], [14, 48]]],
  [28, [[6, 45], [14, 46]]], [28, [[8, 47], [13, 48]]], [28, [[19, 46], [4, 47]]],
  [28, [[22, 45], [3, 46]]], [28, [[3, 45], [23, 46]]], [28, [[21, 45], [7, 46]]],
  [28, [[19, 47], [10, 48]]], [28, [[2, 46], [29, 47]]], [28, [[10, 46], [23, 47]]],
  [28, [[14, 46], [21, 47]]], [28, [[14, 46], [23, 47]]], [28, [[12, 47], [26, 48]]],
  [28, [[6, 47], [34, 48]]], [28, [[29, 46], [14, 47]]], [28, [[13, 46], [32, 47]]],
  [28, [[40, 47], [7, 48]]], [28, [[18, 47], [31, 48]]],
];

/** Alignment-pattern centre coordinates per version. Version 1 has none. */
const ALIGN: ReadonlyArray<readonly number[]> = [
  [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34], [6, 22, 38], [6, 24, 42],
  [6, 26, 46], [6, 28, 50], [6, 30, 54], [6, 32, 58], [6, 34, 62], [6, 26, 46, 66],
  [6, 26, 48, 70], [6, 26, 50, 74], [6, 30, 54, 78], [6, 30, 56, 82], [6, 30, 58, 86],
  [6, 34, 62, 90], [6, 28, 50, 72, 94], [6, 26, 50, 74, 98], [6, 30, 54, 78, 102],
  [6, 28, 54, 80, 106], [6, 32, 58, 84, 110], [6, 30, 58, 86, 114], [6, 34, 62, 90, 118],
  [6, 26, 50, 74, 98, 122], [6, 30, 54, 78, 102, 126], [6, 26, 52, 78, 104, 130],
  [6, 30, 56, 82, 108, 134], [6, 34, 60, 86, 112, 138], [6, 30, 58, 86, 114, 142],
  [6, 34, 62, 90, 118, 146], [6, 30, 54, 78, 102, 126, 150], [6, 24, 50, 76, 102, 128, 154],
  [6, 28, 54, 80, 106, 132, 158], [6, 32, 58, 84, 110, 136, 162],
  [6, 26, 54, 82, 110, 138, 166], [6, 30, 58, 86, 114, 142, 170],
];

// ---------------------------------------------------------------------------
// GF(256) arithmetic, for Reed-Solomon. The field is generated by x^8+x^4+x^3+x^2+1
// (0x11d), the primitive polynomial the QR standard specifies.
// ---------------------------------------------------------------------------

const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]!;
}

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return EXP[LOG[a]! + LOG[b]!]!;
}

/** The generator polynomial for `degree` EC codewords: ∏(x − α^i). */
function generatorPoly(degree: number): Uint8Array {
  let poly = new Uint8Array([1]);
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1);
    for (let j = 0; j < poly.length; j++) {
      next[j] = next[j]! ^ poly[j]!;
      next[j + 1] = next[j + 1]! ^ gfMul(poly[j]!, EXP[i]!);
    }
    poly = next;
  }
  return poly;
}

/** The EC codewords for one data block: the remainder of data·x^degree
 *  divided by the generator polynomial. */
function ecCodewords(data: Uint8Array, degree: number): Uint8Array {
  const gen = generatorPoly(degree);
  const rem = new Uint8Array(data.length + degree);
  rem.set(data);
  for (let i = 0; i < data.length; i++) {
    const factor = rem[i]!;
    if (factor === 0) continue;
    for (let j = 0; j < gen.length; j++) rem[i + j] = rem[i + j]! ^ gfMul(gen[j]!, factor);
  }
  return rem.slice(data.length);
}

// ---------------------------------------------------------------------------
// Bit stream
// ---------------------------------------------------------------------------

class BitBuffer {
  readonly bits: number[] = [];
  put(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  }
}

/** Total data codewords a version holds at level M. */
function dataCapacity(version: number): number {
  const [, groups] = RS_BLOCKS[version - 1]!;
  let total = 0;
  for (const [count, per] of groups) total += count * per;
  return total;
}

/** Byte mode's character-count field is 8 bits up to version 9 and 16 bits
 *  from version 10 — the one place where version changes the header size, and
 *  therefore the one place a naive capacity check goes wrong. */
function countBits(version: number): number {
  return version < 10 ? 8 : 16;
}

/** The smallest version that fits `byteLength` bytes in byte mode at level M. */
function chooseVersion(byteLength: number): number {
  for (let v = 1; v <= 40; v++) {
    // 4 bits of mode indicator + the character count field.
    const needed = 4 + countBits(v) + byteLength * 8;
    if (needed <= dataCapacity(v) * 8) return v;
  }
  throw new Error(`qr: ${byteLength} bytes exceeds the capacity of a version 40 code at level M`);
}

/** Mode indicator, character count, payload, terminator and padding, split
 *  into blocks and interleaved with each block's EC codewords. */
function buildCodewords(bytes: Uint8Array, version: number): Uint8Array {
  const buf = new BitBuffer();
  buf.put(0b0100, 4);                       // byte mode
  buf.put(bytes.length, countBits(version));
  for (const b of bytes) buf.put(b, 8);

  const capacityBits = dataCapacity(version) * 8;
  // Terminator: up to four zero bits, truncated if the code is nearly full.
  buf.put(0, Math.min(4, capacityBits - buf.bits.length));
  while (buf.bits.length % 8 !== 0) buf.bits.push(0);

  const data = new Uint8Array(dataCapacity(version));
  for (let i = 0; i < buf.bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | buf.bits[i + j]!;
    data[i / 8] = byte;
  }
  // The spec's alternating pad bytes fill whatever remains.
  for (let i = buf.bits.length / 8, alt = 0; i < data.length; i++, alt++) {
    data[i] = alt % 2 === 0 ? 0xec : 0x11;
  }

  const [ecPerBlock, groups] = RS_BLOCKS[version - 1]!;
  const dataBlocks: Uint8Array[] = [];
  const ecBlocks: Uint8Array[] = [];
  let offset = 0;
  for (const [count, per] of groups) {
    for (let i = 0; i < count; i++) {
      const block = data.slice(offset, offset + per);
      offset += per;
      dataBlocks.push(block);
      ecBlocks.push(ecCodewords(block, ecPerBlock));
    }
  }

  // Interleave: the nth codeword of every block in turn, data first, then EC.
  // Blocks differ in length by at most one, so the longer ones simply
  // contribute nothing on the final pass.
  const out: number[] = [];
  const maxData = Math.max(...dataBlocks.map((b) => b.length));
  for (let i = 0; i < maxData; i++) {
    for (const block of dataBlocks) if (i < block.length) out.push(block[i]!);
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (const block of ecBlocks) out.push(block[i]!);
  }
  return new Uint8Array(out);
}

// ---------------------------------------------------------------------------
// Matrix
// ---------------------------------------------------------------------------

type Grid = (boolean | null)[][];

function placeFinder(grid: Grid, row: number, col: number): void {
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const rr = row + r;
      const cc = col + c;
      if (rr < 0 || rr >= grid.length || cc < 0 || cc >= grid.length) continue;
      const outer = r >= 0 && r <= 6 && (c === 0 || c === 6);
      const side = c >= 0 && c <= 6 && (r === 0 || r === 6);
      const core = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      grid[rr]![cc] = outer || side || core;
    }
  }
}

/** Format information: 5 data bits (EC level + mask) with BCH(15,5) error
 *  correction, XOR-masked by 0x5412, written twice so either copy can be
 *  read if the other is damaged. */
function formatBits(mask: number): number {
  const data = (0b00 << 3) | mask; // 0b00 is level M
  let rem = data << 10;
  for (let i = 4; i >= 0; i--) {
    if ((rem >>> (i + 10)) & 1) rem ^= 0b10100110111 << i;
  }
  return ((data << 10) | rem) ^ 0b101010000010010;
}

/** Version information for versions 7 and up: 6 data bits with BCH(18,6). */
function versionBits(version: number): number {
  let rem = version << 12;
  for (let i = 5; i >= 0; i--) {
    if ((rem >>> (i + 12)) & 1) rem ^= 0b1111100100101 << i;
  }
  return (version << 12) | rem;
}

function maskAt(mask: number, row: number, col: number): boolean {
  switch (mask) {
    case 0: return (row + col) % 2 === 0;
    case 1: return row % 2 === 0;
    case 2: return col % 3 === 0;
    case 3: return (row + col) % 3 === 0;
    case 4: return (Math.floor(row / 2) + Math.floor(col / 3)) % 2 === 0;
    case 5: return ((row * col) % 2) + ((row * col) % 3) === 0;
    case 6: return (((row * col) % 2) + ((row * col) % 3)) % 2 === 0;
    default: return (((row + col) % 2) + ((row * col) % 3)) % 2 === 0;
  }
}

/** The four penalty rules the standard uses to pick a mask. Lower is better:
 *  they punish long same-colour runs, solid 2×2 blocks, patterns that look
 *  like a finder, and an unbalanced light/dark ratio. */
function penalty(m: boolean[][]): number {
  const n = m.length;
  let score = 0;

  // Rule 1: runs of five or more identical modules, by row and by column.
  for (let i = 0; i < n; i++) {
    for (const byRow of [true, false]) {
      let run = 1;
      for (let j = 1; j < n; j++) {
        const prev = byRow ? m[i]![j - 1]! : m[j - 1]![i]!;
        const cur = byRow ? m[i]![j]! : m[j]![i]!;
        if (cur === prev) {
          run++;
          if (run === 5) score += 3;
          else if (run > 5) score += 1;
        } else run = 1;
      }
    }
  }

  // Rule 2: every 2x2 block of one colour.
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const v = m[r]![c]!;
      if (m[r]![c + 1] === v && m[r + 1]![c] === v && m[r + 1]![c + 1] === v) score += 3;
    }
  }

  // Rule 3: the 1:1:3:1:1 finder-like sequence with four light modules on
  // either side, in both orientations.
  const A = [true, false, true, true, true, false, true, false, false, false, false];
  const B = [false, false, false, false, true, false, true, true, true, false, true];
  for (let i = 0; i < n; i++) {
    for (let j = 0; j + 11 <= n; j++) {
      let rowA = true, rowB = true, colA = true, colB = true;
      for (let k = 0; k < 11; k++) {
        if (m[i]![j + k] !== A[k]) rowA = false;
        if (m[i]![j + k] !== B[k]) rowB = false;
        if (m[j + k]![i] !== A[k]) colA = false;
        if (m[j + k]![i] !== B[k]) colB = false;
      }
      if (rowA) score += 40;
      if (rowB) score += 40;
      if (colA) score += 40;
      if (colB) score += 40;
    }
  }

  // Rule 4: deviation from an even split of dark and light.
  let dark = 0;
  for (const row of m) for (const v of row) if (v) dark++;
  const percent = (dark * 100) / (n * n);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

/** Builds the grid with everything but the data: the function patterns, and
 *  reserved (null) cells where format and version information will go. */
function functionGrid(version: number): Grid {
  const n = version * 4 + 17;
  const grid: Grid = Array.from({ length: n }, () => Array<boolean | null>(n).fill(null));

  placeFinder(grid, 0, 0);
  placeFinder(grid, 0, n - 7);
  placeFinder(grid, n - 7, 0);

  // Timing patterns.
  for (let i = 8; i < n - 8; i++) {
    grid[6]![i] = i % 2 === 0;
    grid[i]![6] = i % 2 === 0;
  }

  // Alignment patterns, except where they would collide with a finder.
  const centres = ALIGN[version - 1]!;
  for (const r of centres) {
    for (const c of centres) {
      if ((r === 6 && c === 6) || (r === 6 && c === n - 7) || (r === n - 7 && c === 6)) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          grid[r + dr]![c + dc] = Math.max(Math.abs(dr), Math.abs(dc)) !== 1;
        }
      }
    }
  }

  // The dark module, always set, always here.
  grid[n - 8]![8] = true;

  // Reserve the format-information strips so data placement skips them.
  for (let i = 0; i < 9; i++) {
    if (grid[8]![i] === null) grid[8]![i] = false;
    if (grid[i]![8] === null) grid[i]![8] = false;
  }
  for (let i = 0; i < 8; i++) {
    if (grid[8]![n - 1 - i] === null) grid[8]![n - 1 - i] = false;
    if (grid[n - 1 - i]![8] === null) grid[n - 1 - i]![8] = false;
  }

  if (version >= 7) {
    const bits = versionBits(version);
    for (let i = 0; i < 18; i++) {
      const bit = ((bits >>> i) & 1) === 1;
      grid[Math.floor(i / 3)]![n - 11 + (i % 3)] = bit;
      grid[n - 11 + (i % 3)]![Math.floor(i / 3)] = bit;
    }
  }

  return grid;
}

/** Walks the data codewords into the grid: two-module-wide columns, right to
 *  left, alternating upward and downward, skipping the vertical timing
 *  pattern and every function module. */
function placeData(grid: Grid, codewords: Uint8Array): void {
  const n = grid.length;
  let bit = 0;
  let upward = true;
  for (let right = n - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5; // the timing column is never part of a data column
    for (let step = 0; step < n; step++) {
      const row = upward ? n - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (grid[row]![col] !== null) continue;
        const byte = codewords[bit >>> 3];
        // Past the last codeword lie the remainder bits, which are always 0.
        grid[row]![col] = byte !== undefined && ((byte >>> (7 - (bit & 7))) & 1) === 1;
        bit++;
      }
    }
    upward = !upward;
  }
}

function writeFormat(m: boolean[][], mask: number): void {
  const n = m.length;
  const bits = formatBits(mask);
  for (let i = 0; i < 15; i++) {
    const bit = ((bits >>> i) & 1) === 1;
    // First copy, around the top-left finder; second split between the other two.
    if (i < 6) m[i]![8] = bit;
    else if (i === 6) m[7]![8] = bit;
    else if (i === 7) m[8]![8] = bit;
    else if (i === 8) m[8]![7] = bit;
    else m[8]![14 - i] = bit;

    if (i < 8) m[8]![n - 1 - i] = bit;
    else m[n - 15 + i]![8] = bit;
  }
}

/**
 * Encodes `text` as a QR code and returns its modules: `matrix[row][col]`,
 * true where the module is dark. No quiet zone — the caller adds it, because
 * how much margin to leave is a rendering decision.
 *
 * `forceMask` overrides the automatic mask choice. Production never passes it;
 * it exists so the conformance test can compare all eight masked symbols
 * against a reference encoder. Mask choice affects only how easily a scanner
 * reads the code, never whether it decodes — the symbol records which mask was
 * used — so pinning it is safe.
 */
export function qrMatrix(text: string, forceMask?: number): boolean[][] {
  const bytes = new TextEncoder().encode(text);
  const version = chooseVersion(bytes.length);
  const codewords = buildCodewords(bytes, version);

  const base = functionGrid(version);
  placeData(base, codewords);

  // Which cells are data (maskable) is a property of the function grid, so it
  // is captured before the data goes in — masking must not touch a function
  // module.
  const reserved = functionGrid(version).map((row) => row.map((v) => v !== null));

  let best: boolean[][] | undefined;
  let bestScore = Infinity;
  for (let mask = 0; mask < 8; mask++) {
    if (forceMask !== undefined && mask !== forceMask) continue;
    const candidate = base.map((row, r) =>
      row.map((v, c) => (reserved[r]![c] ? v === true : (v === true) !== maskAt(mask, r, c))),
    );
    writeFormat(candidate, mask);
    const score = penalty(candidate);
    if (score < bestScore) {
      bestScore = score;
      best = candidate;
    }
  }
  return best!;
}
