/**
 * Build-time thumbnail generation.
 *
 * Renders every registered pattern once, at a fixed seed/size/palette, to a
 * static SVG string, and writes them all to `src/generated/thumbs.ts`. This
 * runs as a `prebuild` step (see package.json) so `npm run build` always
 * regenerates them, and the output is committed so `npm run dev` works
 * without requiring a prior build.
 *
 * Run with: npx vite-node scripts/build-thumbs.ts
 */
import '../src/patterns/index';
import { listPatterns, generateSafe, defaultParams } from '../src/patterns/registry';
import { serialize, type Palette } from '../src/core/svg';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const THUMB_PALETTE: Palette = { paper: '#ffffff', ink: '#1c1b22', accent: '#e3261a' };
const THUMB_SIZE = { w: 240, h: 320 };
const THUMB_SEED = 1;

function build(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const def of listPatterns()) {
    const node = generateSafe(def, defaultParams(def), THUMB_SEED, THUMB_SIZE);
    out[def.id] = serialize(node, THUMB_PALETTE);
  }
  return out;
}

function main(): void {
  const thumbs = build();
  const ids = Object.keys(thumbs).sort();
  const entries = ids.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(thumbs[id])},`).join('\n');
  const banner = '// AUTO-GENERATED by scripts/build-thumbs.ts — do not edit by hand.\n';
  const contents =
    banner +
    '\nexport const THUMBS: Record<string, string> = {\n' +
    entries +
    '\n};\n';

  const here = path.dirname(fileURLToPath(import.meta.url));
  const outPath = path.join(here, '..', 'src', 'generated', 'thumbs.ts');
  writeFileSync(outPath, contents, 'utf-8');
  // eslint-disable-next-line no-console
  console.log(`wrote ${ids.length} thumbnails to ${path.relative(process.cwd(), outPath)}`);
}

main();
