/**
 * Build-time citation extraction.
 *
 * Lifts the `source`/`url` front matter out of every `src/content/explain/
 * <id>.en.md` into a small generated module, so the About page's reference
 * list can name all 30 sources without pulling 30 long-form teaching
 * documents into its bundle — those stay lazily loaded, one at a time, by the
 * pattern that needs them.
 *
 * Generated from the explainers rather than maintained by hand, so a citation
 * can never disagree with the one shown inside the pattern itself. Runs as a
 * `prebuild` step and the output is committed, so `npm run dev` works without
 * a prior build.
 *
 * Run with: npx vite-node scripts/build-references.ts
 */
import { parseFrontMatter } from '../src/content/explain';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const explainDir = path.join(here, '..', 'src', 'content', 'explain');
const outFile = path.join(here, '..', 'src', 'content', 'references.ts');

function main(): void {
  const ids = readdirSync(explainDir)
    .filter((f) => f.endsWith('.en.md'))
    .map((f) => f.replace(/\.en\.md$/, ''))
    .sort();

  const entries = ids.map((id) => {
    const { source, url } = parseFrontMatter(readFileSync(path.join(explainDir, `${id}.en.md`), 'utf-8'));
    return { id, source, url };
  });

  const body = entries
    .map((e) => `  ${JSON.stringify(e.id)}: { source: ${JSON.stringify(e.source)}, url: ${JSON.stringify(e.url)} },`)
    .join('\n');

  const out = `// GENERATED by scripts/build-references.ts — do not edit.
// Source of truth: the front matter of src/content/explain/<id>.en.md.
export interface Reference {
  source: string;
  url: string;
}

export const REFERENCES: Record<string, Reference> = {
${body}
};
`;

  writeFileSync(outFile, out, 'utf-8');
  // eslint-disable-next-line no-console
  console.log(`wrote ${entries.length} references to ${path.relative(process.cwd(), outFile)}`);
}

main();
