/**
 * The pure half of the citation extraction: reads the explain front matter and
 * returns the text of the generated module. Reads nothing else and writes
 * nothing at all.
 *
 * Split from `build-references.ts` so the test suite can import it and assert
 * that the committed `src/content/references.ts` is byte-for-byte what this
 * produces. A CLI entry point that wrote the file on import could not be
 * checked that way — it would rewrite the very file under test — and a test
 * that re-implemented this formatting instead would be a second copy of the
 * rules, which is exactly what generating the table was meant to avoid.
 */
import { parseFrontMatter } from '../src/content/explain';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const explainDir = path.join(here, '..', 'src', 'content', 'explain');

/** Absolute path of the generated module. Named here so the writer and the test that guards it can never point at two different files. */
export const REFERENCES_FILE = path.join(here, '..', 'src', 'content', 'references.ts');

/** Renders the generated module, sorted by pattern id so the output is stable across filesystems and the diff of a real content change stays readable. */
export function renderReferencesModule(): string {
  const ids = readdirSync(explainDir)
    .filter((f) => f.endsWith('.en.md'))
    .map((f) => f.replace(/\.en\.md$/, ''))
    .sort();

  const entries = ids.map((id) => {
    const { source, url, original } = parseFrontMatter(
      readFileSync(path.join(explainDir, `${id}.en.md`), 'utf-8'),
    );
    return { id, source, url, original };
  });

  // `original` is emitted only where it is true, so the table stays a list of
  // citations carrying a few annotations rather than thirty rows of `false`.
  const body = entries
    .map((e) => {
      const own = e.original ? ', original: true' : '';
      return `  ${JSON.stringify(e.id)}: { source: ${JSON.stringify(e.source)}, url: ${JSON.stringify(e.url)}${own} },`;
    })
    .join('\n');

  return `// GENERATED by scripts/build-references.ts — do not edit.
// Source of truth: the front matter of src/content/explain/<id>.en.md.
export interface Reference {
  source: string;
  url: string;
  /** Present and true where the pattern's construction — its composition and
   *  parameterisation — was worked out for this project. The mathematics it
   *  rests on is classical either way, and \`source\` cites it either way. */
  original?: true;
}

export const REFERENCES: Record<string, Reference> = {
${body}
};
`;
}
